In [1]:
import pandas as pd
import requests
import numpy as np
from operator import index
from re import sub
from matplotlib.pyplot import axes
import numpy as np
import requests

In [2]:
link = 'http://app-sellaci.eu-central-1.elasticbeanstalk.com/'

In [3]:
r = requests.get(link)

In [4]:
r

In [5]:
json = r.json()

In [6]:
df = pd.json_normalize(json)

In [7]:
df.head()

,_id,affiliation,areCotationsAuthorized,canChangeBeneficiary,childId,createdAt,customerCreditHasBeenChecked,customerCreditHasBeenDecreased,details,deviceUsedForBooking,...,currentTreatments,hasBeenProposedToUpload,hasCurrentTreatments,mediumUsed,patientHasPriorKnowledge,patientIsReady,patientIsReadyDate,termsAcceptedByPatient,uploadWish,cart.explanation
0,1202019029,qare,False,True,,2020-09-27T21:30:00.116Z,True,False,"Malade: mal de dos, fièvre, vomissements, covid",unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,232323231323212098,qare,True,True,23983099839023,2021-09-27T21:24:00.049Z,True,False,"Trouble du sommeil, tension, douleurs au dos",unknown,...,"Antidépresseur, anxiolitique",True,Y,android - VOG-L29,True,True,2021-09-27T21:25:53.140Z,True,N,always

In [8]:
len(json)

2

In [9]:
df.shape

(2, 96)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 96 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   _id                                                                          2 non-null      object
 1   affiliation                                                                  2 non-null      object
 2   areCotationsAuthorized                                                       2 non-null      bool
 3   canChangeBeneficiary                                                         2 non-null      bool
 4   childId                                                                      2 non-null      object
 5   createdAt                                                                    2 non-null      object
 6   customerCreditHasBeenChecked                                                 2 non-null      bool
 7   customerCreditHasBeenDecreased                                               2 non-null      bool
 8   details                                                                      2 non-null      object
 9   deviceUsedForBooking                                                         2 non-null      object
 10  doctorHasReviewed                                                            2 non-null      bool
 11  doctorId                                                                     2 non-null      object
 12  doctorReminderSent                                                           2 non-null      bool
 13  doctorValidation                                                             2 non-null      bool
 14  estimatedStartDate                                                           2 non-null      object
 15  eventId                                                                      2 non-null      object
 16  facturationId                                                                2 non-null      object
 17  hidePastConsultationsWithOtherPractitioners                                  2 non-null      bool
 18  isEhpad                                                                      2 non-null      bool
 19  isFirstConsultation                                                          2 non-null      bool
 20  isNotConform                                                                 2 non-null      bool
 21  isNotConformReason                                                           2 non-null      object
 22  isSafari                                                                     2 non-null      bool
 23  patientAdministrativeArea                                                    2 non-null      object
 24  patientHasReviewed                                                           2 non-null      bool
 25  patientId                                                                    2 non-null      object
 26  patientPhoneNumber                                                           2 non-null      object
 27  patientReminderSent                                                          2 non-null      bool
 28  paymentIntentStripeId                                                        2 non-null      object
 29  preferredMedium                                                              2 non-null      object
 30  pricingVersion                                                               2 non-null      int64
 31  reminderChecked                                                              2 non-null      bool
 32  reopenCount                                                                  2 non-null      int64
 33  speciality                                                                   2 non-null      object
 34  status                                                                       2 non-null      object
 35  transcriptReminderSent                                                       2 non-null      bool
 36  updatedAt                                                                    2 non-null      object
 37  usePaymentIntent                                                             2 non-null      bool
 38  visitIds                                                                     2 non-null      object
 39  cart.act                                                                     2 non-null      object
 40  cart.actId                                                                   2 non-null      int64
 41  cart.consultationPrice                                                       2 non-null      object
 42  cart.created_at                                                              2 non-null      object
 43  cart.currency                                                                2 non-null      object
 44  cart.customerId                                                              2 non-null      int64
 45  cart.id                                                                      2 non-null      int64
 46  cart.isChargeable                                                            2 non-null      bool
 47  cart.isImmediateCharge                                                       2 non-null      bool
 48  cart.isRequirable                                                            2 non-null      bool
 49  cart.majF                                                                    2 non-null      int64
 50  cart.majMCG                                                                  2 non-null      int64
 51  cart.majMEG                                                                  2 non-null      int64
 52  cart.majMN35                                                                 2 non-null      int64
 53  cart.majMN40                                                                 2 non-null      int64
 54  cart.majMPA                                                                  2 non-null      int64
 55  cart.paymentIntents                                                          2 non-null      object
 56  cart.price                                                                   2 non-null      int64
 57  cart.priceMin                                                                2 non-null      int64
 58  cart.quotedPrice                                                             2 non-null      int64
 59  cart.status                                                                  2 non-null      object
 60  cart.tokenId                                                                 2 non-null      object
 61  cart.updated_at                                                              2 non-null      object
 62  cart.usePaymentIntent                                                        2 non-null      bool
 63  estimatedLength.unit                                                         2 non-null      object
 64  estimatedLength.utc                                                          2 non-null      object
 65  estimatedLength.value                                                        2 non-null      int64
 66  healthCenter.address                                                         1 non-null      object
 67  healthCenter.city                                                            1 non-null      object
 68  healthCenter.finess                                                          1 non-null      object
 69  initiator.role                                                               2 non-null      object
 70  snapshot.beneficiary.hasSocialSecurityNumber                                 2 non-null      bool
 71  snapshot.beneficiary.medicalInsurance.privateInsurance.amcId                 1 non-null      object
 72  snapshot.beneficiary.medicalInsurance.privateInsurance.childMedicalRecordId  1 non-null      object
 73  snapshot.beneficiary.medicalInsurance.privateInsurance.coverageEnd           1 non-null      object
 74  snapshot.beneficiary.medicalInsurance.privateInsurance.coverageStart         1 non-null      object
 75  snapshot.beneficiary.medicalInsurance.privateInsurance.medicalRecordId       1 non-null      object
 76  snapshot.beneficiary.medicalInsurance.privateInsurance.memberId              1 non-null      object
 77  snapshot.beneficiary.medicalInsurance.privateInsurance.scanResult            1 non-null      object
 78  snapshot.beneficiary.medicalInsurance.privateInsurance.verifiedAt            1 non-null      object
 79  snapshot.beneficiary.medicalInsurance.privateInsurance.verifiedStatus        1 non-null      object
 80  snapshot.beneficiary.medicalInsurance.securiteSocialNumber                   2 non-null      object
 81  snapshot.beneficiary.medicalInsurance.verifiedAt                             1 non-null      object
 82  snapshot.beneficiary.medicalInsurance.verifiedStatus                         1 non-null      object
 83  snapshot.consultation.isPartnershipOfferIncluded                             2 non-null      bool
 84  snapshot.doctor.isCME                                                        2 non-null      bool
 85  snapshot.doctor.offer                                                        2 non-null      object
 86  currentTreatments                                                            1 non-null      object
 87  hasBeenProposedToUpload                                                      1 non-null      object
 88  hasCurrentTreatments                                                         1 non-null      object
 89  mediumUsed                                                                   1 non-null      object
 90  patientHasPriorKnowledge                                                     1 non-null      object
 91  patientIsReady                                                               1 non-null      object
 92  patientIsReadyDate                                                           1 non-null      object
 93  termsAcceptedByPatient                                                       1 non-null      object
 94  uploadWish                                                                   1 non-null      object
 95  cart.explanation                                                             1 non-null      object
dtypes: bool(24), int64(15), object(57)
memory usage: 1.3+ KB

In [11]:
df.describe()

,pricingVersion,reopenCount,cart.actId,cart.customerId,cart.id,cart.majF,cart.majMCG,cart.majMEG,cart.majMN35,cart.majMN40,cart.majMPA,cart.price,cart.priceMin,cart.quotedPrice,estimatedLength.value
count,2.0,2.0,2.000000e+00,2.000000,2.000000e+00,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.00000,2.000000
mean,6.0,0.0,4.827726e+06,232317.500000,1.277772e+06,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,12.50000,5.500000
std,0.0,0.0,6.499152e+06,7.778175,1.478504e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.67767,6.363961
min,6.0,0.0,2.321310e+05,232312.000000,2.323110e+05,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,0.00000,1.000000
25%,6.0,0.0,2.529928e+06,232314.750000,7.550412e+05,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,6.25000,3.250000
50%,6.0,0.0,4.827726e+06,232317.500000,1.277772e+06,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,12.50000,5.500000
75%,6.0,0.0,7.125523e+06,232320.250000,1.800502e+06,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,18.75000,7.750000
max,6.0,0.0,9.423320e+06,232323.000000,2.323232e+06,0.0,5.0,0.0,35.0,0.0,0.0,25.0,25.0,25.00000,10.000000

In [12]:
df.isnull().sum()

_id                       0
affiliation               0
areCotationsAuthorized    0
canChangeBeneficiary      0
childId                   0
                         ..
patientIsReady            1
patientIsReadyDate        1
termsAcceptedByPatient    1
uploadWish                1
cart.explanation          1
Length: 96, dtype: int64

In [13]:
# remove nan values
df.dropna(axis=1, inplace=True)
df.shape

(2, 72)

In [14]:
df.columns

Index(['_id', 'affiliation', 'areCotationsAuthorized', 'canChangeBeneficiary',
       'childId', 'createdAt', 'customerCreditHasBeenChecked',
       'customerCreditHasBeenDecreased', 'details', 'deviceUsedForBooking',
       'doctorHasReviewed', 'doctorId', 'doctorReminderSent',
       'doctorValidation', 'estimatedStartDate', 'eventId', 'facturationId',
       'hidePastConsultationsWithOtherPractitioners', 'isEhpad',
       'isFirstConsultation', 'isNotConform', 'isNotConformReason', 'isSafari',
       'patientAdministrativeArea', 'patientHasReviewed', 'patientId',
       'patientPhoneNumber', 'patientReminderSent', 'paymentIntentStripeId',
       'preferredMedium', 'pricingVersion', 'reminderChecked', 'reopenCount',
       'speciality', 'status', 'transcriptReminderSent', 'updatedAt',
       'usePaymentIntent', 'visitIds', 'cart.act', 'cart.actId',
       'cart.consultationPrice', 'cart.created_at', 'cart.currency',
       'cart.customerId', 'cart.id', 'cart.isChargeable',
       'cart.isImmediateCharge', 'cart.isRequirable', 'cart.majF',
       'cart.majMCG', 'cart.majMEG', 'cart.majMN35', 'cart.majMN40',
       'cart.majMPA', 'cart.paymentIntents', 'cart.price', 'cart.priceMin',
       'cart.quotedPrice', 'cart.status', 'cart.tokenId', 'cart.updated_at',
       'cart.usePaymentIntent', 'estimatedLength.unit', 'estimatedLength.utc',
       'estimatedLength.value', 'initiator.role',
       'snapshot.beneficiary.hasSocialSecurityNumber',
       'snapshot.beneficiary.medicalInsurance.securiteSocialNumber',
       'snapshot.consultation.isPartnershipOfferIncluded',
       'snapshot.doctor.isCME', 'snapshot.doctor.offer'],
      dtype='object')

In [15]:
df = df.transpose()

In [16]:
df

,0,1
_id,1202019029,232323231323212098
affiliation,qare,qare
areCotationsAuthorized,False,True
canChangeBeneficiary,True,True
childId,,23983099839023
...,...,...
snapshot.beneficiary.hasSocialSecurityNumber,True,True
snapshot.beneficiary.medicalInsurance.securiteSocialNumber,23232323232311,262129ZZZZ05
snapshot.consultation.isPartnershipOfferIncluded,False,False
snapshot.doctor.isCME,False,False
snapshot.doctor.offer,connect,connect_plus

# Cleaning Data

In [18]:
df = df.rename({0: 'Client 1', 1: 'Client 2'}, axis='columns')
df.head(1)

       Client 1            Client 2
_id  1202019029  232323231323212098

In [19]:
df.reset_index(inplace = True)
df

,index,Client 1,Client 2
0,_id,1202019029,232323231323212098
1,affiliation,qare,qare
2,areCotationsAuthorized,False,True
3,canChangeBeneficiary,True,True
4,childId,,23983099839023
...,...,...,...
67,snapshot.beneficiary.hasSocialSecurityNumber,True,True
68,snapshot.beneficiary.medicalInsurance.securite...,23232323232311,262129ZZZZ05
69,snapshot.consultation.isPartnershipOfferIncluded,False,False
70,snapshot.doctor.isCME,False,False
71,snapshot.doctor.offer,connect,connect_plus

In [20]:
snapshot_rows = df[df['index'].str.contains('snapshot')]['index']
snapshot_rows_clean = snapshot_rows.apply(lambda x: '_'.join(x.split("snapshot.")[1].split("."))).tolist()
col_rename_dict = {i:j for i,j in zip(snapshot_rows, snapshot_rows_clean)}

list_ind = 0
for i in df.index: 
  if df.at[i, 'index'] in snapshot_rows.tolist():
    df.at[i, 'index'] = snapshot_rows_clean[list_ind]
    list_ind += 1
    
df.tail()

,index,Client 1,Client 2
67,beneficiary_hasSocialSecurityNumber,True,True
68,beneficiary_medicalInsurance_securiteSocialNumber,23232323232311,262129ZZZZ05
69,consultation_isPartnershipOfferIncluded,False,False
70,doctor_isCME,False,False
71,doctor_offer,connect,connect_plus

In [21]:
df.dropna(subset=['Client 1', 'Client 2'], inplace=True)
df

,index,Client 1,Client 2
0,_id,1202019029,232323231323212098
1,affiliation,qare,qare
2,areCotationsAuthorized,False,True
3,canChangeBeneficiary,True,True
4,childId,,23983099839023
...,...,...,...
67,beneficiary_hasSocialSecurityNumber,True,True
68,beneficiary_medicalInsurance_securiteSocialNumber,23232323232311,262129ZZZZ05
69,consultation_isPartnershipOfferIncluded,False,False
70,doctor_isCME,False,False
71,doctor_offer,connect,connect_plus

In [22]:
df.columns = ['Information', 'Client 1', 'Client 2']

In [30]:
cart1.set_index(cart1[0], inplace = True)
cart1 = cart1.drop(columns = 0)
cart2 = pd.DataFrame(df['cart'][1].items())
cart2.set_index(cart2[0], inplace = True)
cart2

,0,1
0,,
act,act,consultation
actId,actId,232131
consultationPrice,consultationPrice,
created_at,created_at,2021-09-27T21:23:04.000Z
currency,currency,EUR
customerId,customerId,232312
explanation,explanation,always
id,id,232311
isChargeable,isChargeable,True
isImmediateCharge,isImmediateCharge,False
isRequirable,isRequirable,False
majF,majF,0
majMCG,majMCG,5
majMEG,majMEG,0
majMN35,majMN35,35
majMN40,majMN40,0
majMPA,majMPA,0
paymentIntents,paymentIntents,"[{'amount': 35, 'amountReceived': 0, 'amountRe..."
price,price,25
priceMin,priceMin,25
quotedPrice,quotedPrice,25
status,status,required
tokenId,tokenId,pWI_S
updated_at,updated_at,2021-09-27T21:23:04.000Z
usePaymentIntent,usePaymentIntent,True

In [41]:
cart2 = cart2.drop(columns = 0)

In [37]:
type(cart1)

pandas.core.frame.DataFrame

In [42]:
 cart1.head()

                                          1
0
act                            consultation
actId                               9423320
consultationPrice
created_at         2020-09-26T20:48:27.000Z
currency                                EUR

In [43]:
cart2.head()

                                          1
0
act                            consultation
actId                                232131
consultationPrice
created_at         2021-09-27T21:23:04.000Z
currency                                EUR

In [45]:
df_final = pd.concat([cart1,cart2],axis = 1)
df_final

,1,1
0,,
act,consultation,consultation
actId,9423320,232131
consultationPrice,,
created_at,2020-09-26T20:48:27.000Z,2021-09-27T21:23:04.000Z
currency,EUR,EUR
customerId,232323,232312
id,2323232,232311
isChargeable,False,True
isImmediateCharge,False,False
isRequirable,False,False
majF,0,0
majMCG,5,5
majMEG,0,0
majMN35,35,35
majMN40,0,0
majMPA,0,0
paymentIntents,[],"[{'amount': 35, 'amountReceived': 0, 'amountRe..."
price,25,25
priceMin,25,25
quotedPrice,0,25
status,required,required
tokenId,Hs3330qZR,pWI_S
updated_at,2020-09-26T20:48:27.000Z,2021-09-27T21:23:04.000Z
usePaymentIntent,True,True
explanation,NaN,always

In [33]:
dict = df.loc[df['Information'] == 'cart.paymentIntents']['Client 2'].to_dict()[55][0]
dict

{'amount': 35,
 'amountReceived': 0,
 'amountRefunded': 0,
 'application': '',
 'applicationFee': '500',
 'balanceTransaction': '',
 'captured': False,
 'card_id': '',
 'cartId': 30723292,
 'created_at': '2021-09-27T21:23:00.000Z',
 'currency': 'eur',
 'description': '',
 'destination': 'a1GS23OuGIVsKDKvJJu',
 'dispute': '',
 'failureCode': '',
 'failureMessage': '',
 'id': 76321821,
 'invoiceId': '',
 'payment_method_id': 4583914,
 'refunds': [],
 'status': 'requires_uncapture',
 'stripeId': 'pml1223SpLuC0Xka8T6j',
 'updated_at': '2021-09-27T21:23:04.000Z'}

In [37]:
df_payment_intent = pd.DataFrame.from_dict(dict, orient = 'index')
df_payment_intent

                                           0
amount                                    35
amountReceived                             0
amountRefunded                             0
application
applicationFee                           500
balanceTransaction
captured                               False
card_id
cartId                              30723292
created_at          2021-09-27T21:23:00.000Z
currency                                 eur
description
destination              a1GS23OuGIVsKDKvJJu
dispute
failureCode
failureMessage
id                                  76321821
invoiceId
payment_method_id                    4583914
refunds                                   []
status                    requires_uncapture
stripeId                pml1223SpLuC0Xka8T6j
updated_at          2021-09-27T21:23:04.000Z